-- ══════════════════════════════════════════════════════════════
-- PlanB Market 시드 데이터
--
-- 이 파일은 생성기로 뽑은 것임. 원장 balance_after가 그 시점까지의 누적 잔액이라
-- 손으로 쓰면 거의 확실히 틀림. 회원 잔액도 과거 거래를 다 반영한 결과값이다.
--
-- 시각은 전부 CURRENT_TIMESTAMP 기준 상대값이라 언제 띄워도 시나리오가 성립함.
-- 티켓 1번은 2분 뒤 만료 — 스케줄러가 도는 걸 실시간으로 볼 수 있게 넣어둔 것.
-- ══════════════════════════════════════════════════════════════

-- ─── 회원 5명 (잔액은 초기 충전 500,000 + 과거 거래 정산 반영 결과) ───
INSERT INTO member (id, password, balance, created_at) VALUES ('user01', 'pass1234', 580110, DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO member (id, password, balance, created_at) VALUES ('user02', 'pass1234', 583815, DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO member (id, password, balance, created_at) VALUES ('user03', 'pass1234', 590680, DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO member (id, password, balance, created_at) VALUES ('user04', 'pass1234', 538475, DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO member (id, password, balance, created_at) VALUES ('user05', 'pass1234', 161495, DATEADD('DAY', -40, CURRENT_TIMESTAMP));

-- ─── 티켓 (1~20 활성, 21~35 과거 거래분) ───
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (1, 'user01', 'MOVIE', 'POINT_IN_TIME', '아바타3 IMAX - 용산 CGV', 32000, 2, '8관 E열 14·15번', NULL, DATEADD('MINUTE', 2, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 2, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (2, 'user02', 'CONCERT', 'POINT_IN_TIME', '아이유 콘서트 - 올림픽홀', 264000, 2, 'FLOOR B구역 18열 28·29번', NULL, DATEADD('MINUTE', 120, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 120, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (3, 'user01', 'MOVIE', 'POINT_IN_TIME', '듄 파트3 - 코엑스 메가박스', 28000, 2, '8관 J열 7·8번', NULL, DATEADD('MINUTE', 360, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 360, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (4, 'user03', 'SPORTS', 'POINT_IN_TIME', 'LG vs 두산 - 잠실야구장', 60000, 2, '외야 그린 227블록 9·10번', NULL, DATEADD('MINUTE', 1200, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 1200, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (5, 'user02', 'CONCERT', 'POINT_IN_TIME', '데이식스 콘서트 - KSPO돔', 198000, 2, '스탠딩구역 10열 29·30번', NULL, DATEADD('MINUTE', 4320, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 4320, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (6, 'user04', 'MOVIE', 'POINT_IN_TIME', '인터스텔라 재개봉 - 왕십리', 30000, 2, '4관 E열 10·11번', NULL, DATEADD('MINUTE', 7200, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 7200, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (7, 'user03', 'SPORTS', 'POINT_IN_TIME', '손흥민 자선경기 - 상암', 140000, 2, '1루 내야 290블록 11·12번', NULL, DATEADD('MINUTE', 10080, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 10080, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (8, 'user05', 'EXHIBITION', 'DATE_RANGE', '요시고 사진전 - 그라운드시소', 36000, 2, NULL, NULL, NULL, DATEADD('DAY', -20, CURRENT_DATE), DATEADD('DAY', 10, CURRENT_DATE), NULL, DATEADD('SECOND', 86399, CAST(DATEADD('DAY', 10, CURRENT_DATE) AS TIMESTAMP)), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (9, 'user04', 'TRAIN', 'POINT_IN_TIME', 'KTX 서울→부산 09:00', 59800, 1, '6호차 21석', NULL, DATEADD('MINUTE', 5760, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 5760, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (10, 'user05', 'FLIGHT', 'POINT_IN_TIME', '제주항공 김포→제주 07:20', 78000, 2, '27A, 27B', 2440, DATEADD('MINUTE', 20160, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 20160, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (11, 'user01', 'HOTEL', 'DATE_RANGE', '속초 롯데리조트 디럭스 1박', 180000, 1, NULL, NULL, NULL, DATEADD('DAY', -10, CURRENT_DATE), DATEADD('DAY', 20, CURRENT_DATE), NULL, DATEADD('SECOND', 86399, CAST(DATEADD('DAY', 20, CURRENT_DATE) AS TIMESTAMP)), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (12, 'user02', 'CONCERT', 'POINT_IN_TIME', '잔나비 단독공연 - 올림픽공원', 176000, 2, 'FLOOR A구역 20열 16·17번', NULL, DATEADD('MINUTE', 36000, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 36000, CURRENT_TIMESTAMP), 'OWNED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (13, 'user03', 'MOVIE', 'POINT_IN_TIME', '위키드2 - 신촌 아트레온', 15000, 1, '5관 J열 18번', NULL, DATEADD('MINUTE', 43200, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 43200, CURRENT_TIMESTAMP), 'OWNED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (14, 'user04', 'EXHIBITION', 'DATE_RANGE', '무민 팝업스토어 - 성수', 40000, 2, NULL, NULL, NULL, DATEADD('DAY', -12, CURRENT_DATE), DATEADD('DAY', 18, CURRENT_DATE), NULL, DATEADD('SECOND', 86399, CAST(DATEADD('DAY', 18, CURRENT_DATE) AS TIMESTAMP)), 'OWNED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (15, 'user05', 'TRAIN', 'POINT_IN_TIME', 'SRT 수서→광주송정 14:30', 47500, 1, '4호차 47석', NULL, DATEADD('MINUTE', 17280, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', 17280, CURRENT_TIMESTAMP), 'OWNED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (16, 'user01', 'MOVIE', 'POINT_IN_TIME', '파묘 재상영 - 건대입구', 24000, 2, '8관 F열 10·11번', NULL, DATEADD('MINUTE', -180, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', -180, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (17, 'user02', 'SPORTS', 'POINT_IN_TIME', 'KT vs SSG - 수원KT위즈파크', 25000, 1, '1루 내야 186블록 7번', NULL, DATEADD('MINUTE', -1440, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('MINUTE', -1440, CURRENT_TIMESTAMP), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (18, 'user03', 'EXHIBITION', 'DATE_RANGE', '반 고흐 전시 - DDP', 44000, 2, NULL, NULL, NULL, DATEADD('DAY', -32, CURRENT_DATE), DATEADD('DAY', -2, CURRENT_DATE), NULL, DATEADD('SECOND', 86399, CAST(DATEADD('DAY', -2, CURRENT_DATE) AS TIMESTAMP)), 'LISTED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (19, 'user04', 'GIFTICON', 'EXTENDABLE', '스타벅스 아메리카노 T 2매', 10000, 1, NULL, NULL, NULL, DATEADD('DAY', -60, CURRENT_DATE), DATEADD('DAY', 15, CURRENT_DATE), NULL, DATEADD('SECOND', 86399, CAST(DATEADD('DAY', 15, CURRENT_DATE) AS TIMESTAMP)), 'OWNED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (20, 'user05', 'GIFTICON', 'EXTENDABLE', '배스킨라빈스 파인트 교환권', 12000, 1, NULL, NULL, NULL, DATEADD('DAY', -60, CURRENT_DATE), DATEADD('DAY', 10, CURRENT_DATE), DATEADD('DAY', 40, CURRENT_DATE), DATEADD('SECOND', 86399, CAST(DATEADD('DAY', 40, CURRENT_DATE) AS TIMESTAMP)), 'OWNED', NULL, DATEADD('DAY', -35, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (21, 'user02', 'MOVIE', 'POINT_IN_TIME', '범죄도시5 - 홍대 CGV', 30000, 2, '8관 H열 5·6번', NULL, DATEADD('HOUR', -600, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -600, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -656, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (22, 'user04', 'CONCERT', 'POINT_IN_TIME', '김광석 다시부르기 - 세종문화회관', 180000, 2, 'FLOOR A구역 11열 2·3번', NULL, DATEADD('HOUR', -500, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -500, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -554, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (23, 'user01', 'SPORTS', 'POINT_IN_TIME', '한화 vs 롯데 - 대전', 50000, 2, '중앙 지정 223블록 19·20번', NULL, DATEADD('HOUR', -420, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -420, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -478, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (24, 'user03', 'MOVIE', 'POINT_IN_TIME', '서울의봄 재개봉 - 압구정', 28000, 2, '4관 E열 3·4번', NULL, DATEADD('HOUR', -360, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -360, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -448, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (25, 'user05', 'CONCERT', 'POINT_IN_TIME', '10CM 소극장 - 블루스퀘어', 120000, 2, 'FLOOR B구역 19열 9·10번', NULL, DATEADD('HOUR', -300, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -300, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -396, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (26, 'user03', 'TRAIN', 'POINT_IN_TIME', 'KTX 서울→동대구 18:00', 43500, 1, '6호차 47석', NULL, DATEADD('HOUR', -260, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -260, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -344, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (27, 'user02', 'MOVIE', 'POINT_IN_TIME', '오펜하이머 IMAX - 용산', 34000, 2, '2관 G열 7·8번', NULL, DATEADD('HOUR', -220, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -220, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -364, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (28, 'user01', 'SPORTS', 'POINT_IN_TIME', 'KIA vs 삼성 - 광주', 56000, 2, '1루 내야 266블록 1·2번', NULL, DATEADD('HOUR', -190, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -190, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -358, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (29, 'user04', 'EXHIBITION', 'DATE_RANGE', 'David Hockney 전 - 예술의전당', 40000, 2, NULL, NULL, NULL, DATEADD('DAY', -34, CURRENT_DATE), DATEADD('DAY', -4, CURRENT_DATE), NULL, DATEADD('SECOND', 86399, CAST(DATEADD('DAY', -4, CURRENT_DATE) AS TIMESTAMP)), 'TRANSFERRED', NULL, DATEADD('HOUR', -234, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (30, 'user01', 'FLIGHT', 'POINT_IN_TIME', '대한항공 김포→여수 11:10', 92000, 1, '35H', 1440, DATEADD('HOUR', -160, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -160, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -318, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (31, 'user05', 'CONCERT', 'POINT_IN_TIME', 'IU 앵콜 - 고척돔', 220000, 2, '2층 C구역 7열 12·13번', NULL, DATEADD('HOUR', -140, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -140, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -388, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (32, 'user03', 'MOVIE', 'POINT_IN_TIME', '듄2 재상영 - 코엑스', 32000, 2, '2관 D열 9·10번', NULL, DATEADD('HOUR', -120, CURRENT_TIMESTAMP), NULL, NULL, NULL, DATEADD('HOUR', -120, CURRENT_TIMESTAMP), 'TRANSFERRED', NULL, DATEADD('HOUR', -378, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (33, 'user05', 'HOTEL', 'DATE_RANGE', '여수 베네치아호텔 1박', 150000, 1, NULL, NULL, NULL, DATEADD('DAY', -36, CURRENT_DATE), DATEADD('DAY', -6, CURRENT_DATE), NULL, DATEADD('SECOND', 86399, CAST(DATEADD('DAY', -6, CURRENT_DATE) AS TIMESTAMP)), 'TRANSFERRED', NULL, DATEADD('HOUR', -392, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (34, 'user02', 'EXHIBITION', 'DATE_RANGE', '팀랩 전시 - 아르떼뮤지엄', 52000, 2, NULL, NULL, NULL, DATEADD('DAY', -38, CURRENT_DATE), DATEADD('DAY', -8, CURRENT_DATE), NULL, DATEADD('SECOND', 86399, CAST(DATEADD('DAY', -8, CURRENT_DATE) AS TIMESTAMP)), 'TRANSFERRED', NULL, DATEADD('HOUR', -440, CURRENT_TIMESTAMP));
INSERT INTO ticket (id, owner_id, category, expiry_type, title, original_price, quantity, seat_info, mileage, event_at, valid_from, valid_until, extended_until, expires_at, status, expiry_warned_at, created_at) VALUES (35, 'user04', 'GIFTICON', 'EXTENDABLE', '교촌치킨 허니콤보 교환권', 23000, 1, NULL, NULL, NULL, DATEADD('DAY', -40, CURRENT_DATE), DATEADD('DAY', -10, CURRENT_DATE), NULL, DATEADD('SECOND', 86399, CAST(DATEADD('DAY', -10, CURRENT_DATE) AS TIMESTAMP)), 'TRANSFERRED', NULL, DATEADD('HOUR', -508, CURRENT_TIMESTAMP));

-- ─── 판매 등록 ───
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (1, 1, 'user01', 25600, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (2, 2, 'user02', 211200, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (3, 3, 'user01', 22400, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (4, 4, 'user03', 48000, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (5, 5, 'user02', 158400, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (6, 6, 'user04', 24000, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (7, 7, 'user03', 112000, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (8, 8, 'user05', 28800, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (9, 9, 'user04', 47800, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (10, 10, 'user05', 62400, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (11, 11, 'user01', 144000, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (16, 16, 'user01', 19200, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (17, 17, 'user02', 20000, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (18, 18, 'user03', 35200, 'OPEN', DATEADD('DAY', -3, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (21, 21, 'user01', 17400, 'COMPLETED', DATEADD('HOUR', -632, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (22, 22, 'user03', 111600, 'COMPLETED', DATEADD('HOUR', -530, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (23, 23, 'user05', 30000, 'COMPLETED', DATEADD('HOUR', -454, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (24, 24, 'user02', 20200, 'COMPLETED', DATEADD('HOUR', -424, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (25, 25, 'user04', 88800, 'COMPLETED', DATEADD('HOUR', -372, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (26, 26, 'user01', 30400, 'COMPLETED', DATEADD('HOUR', -320, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (27, 27, 'user05', 27900, 'COMPLETED', DATEADD('HOUR', -340, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (28, 28, 'user03', 47000, 'COMPLETED', DATEADD('HOUR', -334, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (29, 29, 'user02', 32000, 'COMPLETED', DATEADD('HOUR', -210, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (30, 30, 'user04', 76400, 'COMPLETED', DATEADD('HOUR', -294, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (31, 31, 'user01', 198000, 'COMPLETED', DATEADD('HOUR', -364, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (32, 32, 'user05', 28200, 'COMPLETED', DATEADD('HOUR', -354, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (33, 33, 'user02', 133500, 'COMPLETED', DATEADD('HOUR', -368, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (34, 34, 'user04', 47300, 'COMPLETED', DATEADD('HOUR', -416, CURRENT_TIMESTAMP));
INSERT INTO listing (id, ticket_id, seller_id, asking_price, status, created_at) VALUES (35, 35, 'user03', 19800, 'COMPLETED', DATEADD('HOUR', -484, CURRENT_TIMESTAMP));

-- ─── 완료된 과거 거래 15건 (가격 추천 통계의 표본) ───
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (1, 21, 'user02', 2, 17400, 'CONFIRMED', DATEADD('HOUR', -608, CURRENT_TIMESTAMP), DATEADD('HOUR', -600, CURRENT_TIMESTAMP), DATEADD('HOUR', -606, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (2, 22, 'user04', 2, 111600, 'CONFIRMED', DATEADD('HOUR', -506, CURRENT_TIMESTAMP), DATEADD('HOUR', -500, CURRENT_TIMESTAMP), DATEADD('HOUR', -504, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (3, 23, 'user01', 2, 30000, 'CONFIRMED', DATEADD('HOUR', -430, CURRENT_TIMESTAMP), DATEADD('HOUR', -420, CURRENT_TIMESTAMP), DATEADD('HOUR', -428, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (4, 24, 'user03', 2, 20200, 'CONFIRMED', DATEADD('HOUR', -400, CURRENT_TIMESTAMP), DATEADD('HOUR', -376, CURRENT_TIMESTAMP), DATEADD('HOUR', -398, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (5, 25, 'user05', 2, 88800, 'CONFIRMED', DATEADD('HOUR', -348, CURRENT_TIMESTAMP), DATEADD('HOUR', -324, CURRENT_TIMESTAMP), DATEADD('HOUR', -346, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (6, 26, 'user03', 1, 30400, 'CONFIRMED', DATEADD('HOUR', -296, CURRENT_TIMESTAMP), DATEADD('HOUR', -272, CURRENT_TIMESTAMP), DATEADD('HOUR', -294, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (7, 27, 'user02', 2, 27900, 'CONFIRMED', DATEADD('HOUR', -316, CURRENT_TIMESTAMP), DATEADD('HOUR', -292, CURRENT_TIMESTAMP), DATEADD('HOUR', -314, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (8, 28, 'user01', 2, 47000, 'CONFIRMED', DATEADD('HOUR', -310, CURRENT_TIMESTAMP), DATEADD('HOUR', -286, CURRENT_TIMESTAMP), DATEADD('HOUR', -308, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (9, 29, 'user04', 2, 32000, 'CONFIRMED', DATEADD('HOUR', -186, CURRENT_TIMESTAMP), DATEADD('HOUR', -162, CURRENT_TIMESTAMP), DATEADD('HOUR', -184, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (10, 30, 'user01', 1, 76400, 'CONFIRMED', DATEADD('HOUR', -270, CURRENT_TIMESTAMP), DATEADD('HOUR', -246, CURRENT_TIMESTAMP), DATEADD('HOUR', -268, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (11, 31, 'user05', 2, 198000, 'CONFIRMED', DATEADD('HOUR', -340, CURRENT_TIMESTAMP), DATEADD('HOUR', -316, CURRENT_TIMESTAMP), DATEADD('HOUR', -338, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (12, 32, 'user03', 2, 28200, 'CONFIRMED', DATEADD('HOUR', -330, CURRENT_TIMESTAMP), DATEADD('HOUR', -306, CURRENT_TIMESTAMP), DATEADD('HOUR', -328, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (13, 33, 'user05', 1, 133500, 'CONFIRMED', DATEADD('HOUR', -344, CURRENT_TIMESTAMP), DATEADD('HOUR', -320, CURRENT_TIMESTAMP), DATEADD('HOUR', -342, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (14, 34, 'user02', 2, 47300, 'CONFIRMED', DATEADD('HOUR', -392, CURRENT_TIMESTAMP), DATEADD('HOUR', -368, CURRENT_TIMESTAMP), DATEADD('HOUR', -390, CURRENT_TIMESTAMP));
INSERT INTO escrow (id, listing_id, buyer_id, quantity, amount, status, paid_at, auto_confirm_at, confirmed_at) VALUES (15, 35, 'user04', 1, 19800, 'CONFIRMED', DATEADD('HOUR', -460, CURRENT_TIMESTAMP), DATEADD('HOUR', -436, CURRENT_TIMESTAMP), DATEADD('HOUR', -458, CURRENT_TIMESTAMP));

-- ─── 원장 ───
-- 모든 금전 이동이 DEBIT 1줄 + CREDIT 1줄 쌍으로 들어가 있음.
-- 그래서 SUM(DEBIT) = SUM(CREDIT)이 시드 상태에서 이미 성립함.
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (1, 'EXTERNAL', 'DEBIT', 500000, -500000, 'CHARGE', 'CHARGE', NULL, '가입 예치금 충전', DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (2, 'user01', 'CREDIT', 500000, 500000, 'CHARGE', 'CHARGE', NULL, '가입 예치금 충전', DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (3, 'EXTERNAL', 'DEBIT', 500000, -1000000, 'CHARGE', 'CHARGE', NULL, '가입 예치금 충전', DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (4, 'user02', 'CREDIT', 500000, 500000, 'CHARGE', 'CHARGE', NULL, '가입 예치금 충전', DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (5, 'EXTERNAL', 'DEBIT', 500000, -1500000, 'CHARGE', 'CHARGE', NULL, '가입 예치금 충전', DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (6, 'user03', 'CREDIT', 500000, 500000, 'CHARGE', 'CHARGE', NULL, '가입 예치금 충전', DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (7, 'EXTERNAL', 'DEBIT', 500000, -2000000, 'CHARGE', 'CHARGE', NULL, '가입 예치금 충전', DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (8, 'user04', 'CREDIT', 500000, 500000, 'CHARGE', 'CHARGE', NULL, '가입 예치금 충전', DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (9, 'EXTERNAL', 'DEBIT', 500000, -2500000, 'CHARGE', 'CHARGE', NULL, '가입 예치금 충전', DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (10, 'user05', 'CREDIT', 500000, 500000, 'CHARGE', 'CHARGE', NULL, '가입 예치금 충전', DATEADD('DAY', -40, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (11, 'user02', 'DEBIT', 17400, 482600, 'PURCHASE', 'ESCROW', 1, '티켓 구매 결제', DATEADD('HOUR', -608, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (12, 'ESCROW_POOL', 'CREDIT', 17400, 17400, 'PURCHASE', 'ESCROW', 1, '티켓 구매 결제', DATEADD('HOUR', -608, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (13, 'ESCROW_POOL', 'DEBIT', 870, 16530, 'COMMISSION', 'ESCROW', 1, '중개 수수료 5%', DATEADD('HOUR', -606, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (14, 'PLATFORM', 'CREDIT', 870, 870, 'COMMISSION', 'ESCROW', 1, '중개 수수료 5%', DATEADD('HOUR', -606, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (15, 'ESCROW_POOL', 'DEBIT', 16530, 0, 'SELLER_SETTLE', 'ESCROW', 1, '거래 확정 정산', DATEADD('HOUR', -606, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (16, 'user01', 'CREDIT', 16530, 516530, 'SELLER_SETTLE', 'ESCROW', 1, '거래 확정 정산', DATEADD('HOUR', -606, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (17, 'user04', 'DEBIT', 111600, 388400, 'PURCHASE', 'ESCROW', 2, '티켓 구매 결제', DATEADD('HOUR', -506, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (18, 'ESCROW_POOL', 'CREDIT', 111600, 111600, 'PURCHASE', 'ESCROW', 2, '티켓 구매 결제', DATEADD('HOUR', -506, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (19, 'ESCROW_POOL', 'DEBIT', 5580, 106020, 'COMMISSION', 'ESCROW', 2, '중개 수수료 5%', DATEADD('HOUR', -504, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (20, 'PLATFORM', 'CREDIT', 5580, 6450, 'COMMISSION', 'ESCROW', 2, '중개 수수료 5%', DATEADD('HOUR', -504, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (21, 'ESCROW_POOL', 'DEBIT', 106020, 0, 'SELLER_SETTLE', 'ESCROW', 2, '거래 확정 정산', DATEADD('HOUR', -504, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (22, 'user03', 'CREDIT', 106020, 606020, 'SELLER_SETTLE', 'ESCROW', 2, '거래 확정 정산', DATEADD('HOUR', -504, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (23, 'user04', 'DEBIT', 19800, 368600, 'PURCHASE', 'ESCROW', 15, '티켓 구매 결제', DATEADD('HOUR', -460, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (24, 'ESCROW_POOL', 'CREDIT', 19800, 19800, 'PURCHASE', 'ESCROW', 15, '티켓 구매 결제', DATEADD('HOUR', -460, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (25, 'ESCROW_POOL', 'DEBIT', 990, 18810, 'COMMISSION', 'ESCROW', 15, '중개 수수료 5%', DATEADD('HOUR', -458, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (26, 'PLATFORM', 'CREDIT', 990, 7440, 'COMMISSION', 'ESCROW', 15, '중개 수수료 5%', DATEADD('HOUR', -458, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (27, 'ESCROW_POOL', 'DEBIT', 18810, 0, 'SELLER_SETTLE', 'ESCROW', 15, '거래 확정 정산', DATEADD('HOUR', -458, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (28, 'user03', 'CREDIT', 18810, 624830, 'SELLER_SETTLE', 'ESCROW', 15, '거래 확정 정산', DATEADD('HOUR', -458, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (29, 'user01', 'DEBIT', 30000, 486530, 'PURCHASE', 'ESCROW', 3, '티켓 구매 결제', DATEADD('HOUR', -430, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (30, 'ESCROW_POOL', 'CREDIT', 30000, 30000, 'PURCHASE', 'ESCROW', 3, '티켓 구매 결제', DATEADD('HOUR', -430, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (31, 'ESCROW_POOL', 'DEBIT', 1500, 28500, 'COMMISSION', 'ESCROW', 3, '중개 수수료 5%', DATEADD('HOUR', -428, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (32, 'PLATFORM', 'CREDIT', 1500, 8940, 'COMMISSION', 'ESCROW', 3, '중개 수수료 5%', DATEADD('HOUR', -428, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (33, 'ESCROW_POOL', 'DEBIT', 28500, 0, 'SELLER_SETTLE', 'ESCROW', 3, '거래 확정 정산', DATEADD('HOUR', -428, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (34, 'user05', 'CREDIT', 28500, 528500, 'SELLER_SETTLE', 'ESCROW', 3, '거래 확정 정산', DATEADD('HOUR', -428, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (35, 'user03', 'DEBIT', 20200, 604630, 'PURCHASE', 'ESCROW', 4, '티켓 구매 결제', DATEADD('HOUR', -400, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (36, 'ESCROW_POOL', 'CREDIT', 20200, 20200, 'PURCHASE', 'ESCROW', 4, '티켓 구매 결제', DATEADD('HOUR', -400, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (37, 'ESCROW_POOL', 'DEBIT', 1010, 19190, 'COMMISSION', 'ESCROW', 4, '중개 수수료 5%', DATEADD('HOUR', -398, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (38, 'PLATFORM', 'CREDIT', 1010, 9950, 'COMMISSION', 'ESCROW', 4, '중개 수수료 5%', DATEADD('HOUR', -398, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (39, 'ESCROW_POOL', 'DEBIT', 19190, 0, 'SELLER_SETTLE', 'ESCROW', 4, '거래 확정 정산', DATEADD('HOUR', -398, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (40, 'user02', 'CREDIT', 19190, 501790, 'SELLER_SETTLE', 'ESCROW', 4, '거래 확정 정산', DATEADD('HOUR', -398, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (41, 'user02', 'DEBIT', 47300, 454490, 'PURCHASE', 'ESCROW', 14, '티켓 구매 결제', DATEADD('HOUR', -392, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (42, 'ESCROW_POOL', 'CREDIT', 47300, 47300, 'PURCHASE', 'ESCROW', 14, '티켓 구매 결제', DATEADD('HOUR', -392, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (43, 'ESCROW_POOL', 'DEBIT', 2365, 44935, 'COMMISSION', 'ESCROW', 14, '중개 수수료 5%', DATEADD('HOUR', -390, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (44, 'PLATFORM', 'CREDIT', 2365, 12315, 'COMMISSION', 'ESCROW', 14, '중개 수수료 5%', DATEADD('HOUR', -390, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (45, 'ESCROW_POOL', 'DEBIT', 44935, 0, 'SELLER_SETTLE', 'ESCROW', 14, '거래 확정 정산', DATEADD('HOUR', -390, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (46, 'user04', 'CREDIT', 44935, 413535, 'SELLER_SETTLE', 'ESCROW', 14, '거래 확정 정산', DATEADD('HOUR', -390, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (47, 'user05', 'DEBIT', 88800, 439700, 'PURCHASE', 'ESCROW', 5, '티켓 구매 결제', DATEADD('HOUR', -348, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (48, 'ESCROW_POOL', 'CREDIT', 88800, 88800, 'PURCHASE', 'ESCROW', 5, '티켓 구매 결제', DATEADD('HOUR', -348, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (49, 'ESCROW_POOL', 'DEBIT', 4440, 84360, 'COMMISSION', 'ESCROW', 5, '중개 수수료 5%', DATEADD('HOUR', -346, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (50, 'PLATFORM', 'CREDIT', 4440, 16755, 'COMMISSION', 'ESCROW', 5, '중개 수수료 5%', DATEADD('HOUR', -346, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (51, 'ESCROW_POOL', 'DEBIT', 84360, 0, 'SELLER_SETTLE', 'ESCROW', 5, '거래 확정 정산', DATEADD('HOUR', -346, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (52, 'user04', 'CREDIT', 84360, 497895, 'SELLER_SETTLE', 'ESCROW', 5, '거래 확정 정산', DATEADD('HOUR', -346, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (53, 'user05', 'DEBIT', 133500, 306200, 'PURCHASE', 'ESCROW', 13, '티켓 구매 결제', DATEADD('HOUR', -344, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (54, 'ESCROW_POOL', 'CREDIT', 133500, 133500, 'PURCHASE', 'ESCROW', 13, '티켓 구매 결제', DATEADD('HOUR', -344, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (55, 'ESCROW_POOL', 'DEBIT', 6675, 126825, 'COMMISSION', 'ESCROW', 13, '중개 수수료 5%', DATEADD('HOUR', -342, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (56, 'PLATFORM', 'CREDIT', 6675, 23430, 'COMMISSION', 'ESCROW', 13, '중개 수수료 5%', DATEADD('HOUR', -342, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (57, 'ESCROW_POOL', 'DEBIT', 126825, 0, 'SELLER_SETTLE', 'ESCROW', 13, '거래 확정 정산', DATEADD('HOUR', -342, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (58, 'user02', 'CREDIT', 126825, 581315, 'SELLER_SETTLE', 'ESCROW', 13, '거래 확정 정산', DATEADD('HOUR', -342, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (59, 'user05', 'DEBIT', 198000, 108200, 'PURCHASE', 'ESCROW', 11, '티켓 구매 결제', DATEADD('HOUR', -340, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (60, 'ESCROW_POOL', 'CREDIT', 198000, 198000, 'PURCHASE', 'ESCROW', 11, '티켓 구매 결제', DATEADD('HOUR', -340, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (61, 'ESCROW_POOL', 'DEBIT', 9900, 188100, 'COMMISSION', 'ESCROW', 11, '중개 수수료 5%', DATEADD('HOUR', -338, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (62, 'PLATFORM', 'CREDIT', 9900, 33330, 'COMMISSION', 'ESCROW', 11, '중개 수수료 5%', DATEADD('HOUR', -338, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (63, 'ESCROW_POOL', 'DEBIT', 188100, 0, 'SELLER_SETTLE', 'ESCROW', 11, '거래 확정 정산', DATEADD('HOUR', -338, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (64, 'user01', 'CREDIT', 188100, 674630, 'SELLER_SETTLE', 'ESCROW', 11, '거래 확정 정산', DATEADD('HOUR', -338, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (65, 'user03', 'DEBIT', 28200, 576430, 'PURCHASE', 'ESCROW', 12, '티켓 구매 결제', DATEADD('HOUR', -330, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (66, 'ESCROW_POOL', 'CREDIT', 28200, 28200, 'PURCHASE', 'ESCROW', 12, '티켓 구매 결제', DATEADD('HOUR', -330, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (67, 'ESCROW_POOL', 'DEBIT', 1410, 26790, 'COMMISSION', 'ESCROW', 12, '중개 수수료 5%', DATEADD('HOUR', -328, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (68, 'PLATFORM', 'CREDIT', 1410, 34740, 'COMMISSION', 'ESCROW', 12, '중개 수수료 5%', DATEADD('HOUR', -328, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (69, 'ESCROW_POOL', 'DEBIT', 26790, 0, 'SELLER_SETTLE', 'ESCROW', 12, '거래 확정 정산', DATEADD('HOUR', -328, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (70, 'user05', 'CREDIT', 26790, 134990, 'SELLER_SETTLE', 'ESCROW', 12, '거래 확정 정산', DATEADD('HOUR', -328, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (71, 'user02', 'DEBIT', 27900, 553415, 'PURCHASE', 'ESCROW', 7, '티켓 구매 결제', DATEADD('HOUR', -316, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (72, 'ESCROW_POOL', 'CREDIT', 27900, 27900, 'PURCHASE', 'ESCROW', 7, '티켓 구매 결제', DATEADD('HOUR', -316, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (73, 'ESCROW_POOL', 'DEBIT', 1395, 26505, 'COMMISSION', 'ESCROW', 7, '중개 수수료 5%', DATEADD('HOUR', -314, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (74, 'PLATFORM', 'CREDIT', 1395, 36135, 'COMMISSION', 'ESCROW', 7, '중개 수수료 5%', DATEADD('HOUR', -314, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (75, 'ESCROW_POOL', 'DEBIT', 26505, 0, 'SELLER_SETTLE', 'ESCROW', 7, '거래 확정 정산', DATEADD('HOUR', -314, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (76, 'user05', 'CREDIT', 26505, 161495, 'SELLER_SETTLE', 'ESCROW', 7, '거래 확정 정산', DATEADD('HOUR', -314, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (77, 'user01', 'DEBIT', 47000, 627630, 'PURCHASE', 'ESCROW', 8, '티켓 구매 결제', DATEADD('HOUR', -310, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (78, 'ESCROW_POOL', 'CREDIT', 47000, 47000, 'PURCHASE', 'ESCROW', 8, '티켓 구매 결제', DATEADD('HOUR', -310, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (79, 'ESCROW_POOL', 'DEBIT', 2350, 44650, 'COMMISSION', 'ESCROW', 8, '중개 수수료 5%', DATEADD('HOUR', -308, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (80, 'PLATFORM', 'CREDIT', 2350, 38485, 'COMMISSION', 'ESCROW', 8, '중개 수수료 5%', DATEADD('HOUR', -308, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (81, 'ESCROW_POOL', 'DEBIT', 44650, 0, 'SELLER_SETTLE', 'ESCROW', 8, '거래 확정 정산', DATEADD('HOUR', -308, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (82, 'user03', 'CREDIT', 44650, 621080, 'SELLER_SETTLE', 'ESCROW', 8, '거래 확정 정산', DATEADD('HOUR', -308, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (83, 'user03', 'DEBIT', 30400, 590680, 'PURCHASE', 'ESCROW', 6, '티켓 구매 결제', DATEADD('HOUR', -296, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (84, 'ESCROW_POOL', 'CREDIT', 30400, 30400, 'PURCHASE', 'ESCROW', 6, '티켓 구매 결제', DATEADD('HOUR', -296, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (85, 'ESCROW_POOL', 'DEBIT', 1520, 28880, 'COMMISSION', 'ESCROW', 6, '중개 수수료 5%', DATEADD('HOUR', -294, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (86, 'PLATFORM', 'CREDIT', 1520, 40005, 'COMMISSION', 'ESCROW', 6, '중개 수수료 5%', DATEADD('HOUR', -294, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (87, 'ESCROW_POOL', 'DEBIT', 28880, 0, 'SELLER_SETTLE', 'ESCROW', 6, '거래 확정 정산', DATEADD('HOUR', -294, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (88, 'user01', 'CREDIT', 28880, 656510, 'SELLER_SETTLE', 'ESCROW', 6, '거래 확정 정산', DATEADD('HOUR', -294, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (89, 'user01', 'DEBIT', 76400, 580110, 'PURCHASE', 'ESCROW', 10, '티켓 구매 결제', DATEADD('HOUR', -270, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (90, 'ESCROW_POOL', 'CREDIT', 76400, 76400, 'PURCHASE', 'ESCROW', 10, '티켓 구매 결제', DATEADD('HOUR', -270, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (91, 'ESCROW_POOL', 'DEBIT', 3820, 72580, 'COMMISSION', 'ESCROW', 10, '중개 수수료 5%', DATEADD('HOUR', -268, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (92, 'PLATFORM', 'CREDIT', 3820, 43825, 'COMMISSION', 'ESCROW', 10, '중개 수수료 5%', DATEADD('HOUR', -268, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (93, 'ESCROW_POOL', 'DEBIT', 72580, 0, 'SELLER_SETTLE', 'ESCROW', 10, '거래 확정 정산', DATEADD('HOUR', -268, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (94, 'user04', 'CREDIT', 72580, 570475, 'SELLER_SETTLE', 'ESCROW', 10, '거래 확정 정산', DATEADD('HOUR', -268, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (95, 'user04', 'DEBIT', 32000, 538475, 'PURCHASE', 'ESCROW', 9, '티켓 구매 결제', DATEADD('HOUR', -186, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (96, 'ESCROW_POOL', 'CREDIT', 32000, 32000, 'PURCHASE', 'ESCROW', 9, '티켓 구매 결제', DATEADD('HOUR', -186, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (97, 'ESCROW_POOL', 'DEBIT', 1600, 30400, 'COMMISSION', 'ESCROW', 9, '중개 수수료 5%', DATEADD('HOUR', -184, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (98, 'PLATFORM', 'CREDIT', 1600, 45425, 'COMMISSION', 'ESCROW', 9, '중개 수수료 5%', DATEADD('HOUR', -184, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (99, 'ESCROW_POOL', 'DEBIT', 30400, 0, 'SELLER_SETTLE', 'ESCROW', 9, '거래 확정 정산', DATEADD('HOUR', -184, CURRENT_TIMESTAMP));
INSERT INTO ledger (id, account_id, entry_type, amount, balance_after, reason, ref_type, ref_id, memo, created_at) VALUES (100, 'user02', 'CREDIT', 30400, 583815, 'SELLER_SETTLE', 'ESCROW', 9, '거래 확정 정산', DATEADD('HOUR', -184, CURRENT_TIMESTAMP));

-- ─── 식별자 시퀀스 재시작 ───
-- 시드는 id를 직접 박아 넣어서 IDENTITY 카운터가 그대로 1에 머물러 있음.
-- 안 맞춰주면 앱에서 첫 INSERT를 할 때 PK가 겹쳐서 터짐.
ALTER TABLE ticket ALTER COLUMN id RESTART WITH 100;
ALTER TABLE listing ALTER COLUMN id RESTART WITH 100;
ALTER TABLE escrow ALTER COLUMN id RESTART WITH 100;
ALTER TABLE ledger ALTER COLUMN id RESTART WITH 201;
